version: '3.8'

services:
  # MongoDB Database (same as production)
  mongodb:
    image: mongo:7.0
    container_name: todoapp-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: TodoAppDb
    volumes:
      - mongodb_dev_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - todoapp-dev-network

volumes:
  mongodb_dev_data:

networks:
  todoapp-dev-network:
    driver: bridge
